# Generated by Django 5.2.9 on 2026-01-11 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourlife_social', '0003_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BULLYING', 'Bullying ou Assédio'), ('SPAM', 'Spam ou Golpe'), ('VIOLENCIA', 'Violência ou Ameaça'), ('OUTRO', 'Outro Motivo')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
